eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
     
microservice:
  client1-service:
    endpoints:
      endpoint:
        uri: http://PARTS-ORDER-CLIENT-APP/parts/order/v1/getPartsOrderList
        
microservice:
  client2-service:
    endpoints:
      endpoint:
        uri: http://PARTS-ORDER-MANAGEMENT-APP/parts/management/v1/validateOrder
