eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  
spring:
  cloud:
    gateway:
      routes:
        - id: PARTS-ORDER-CLIENT-APP
          uri: lb://PARTS-ORDER-CLIENT-APP
          predicates:
            - Path=/parts/order/v1/**
        - id: PARTS-ORDER-MANAGEMENT-APP
          uri: lb://PARTS-ORDER-MANAGEMENT-APP
          predicates:
            - Path=/parts/management/v1/**
     
microservice:
  client1-service:
    endpoints:
      endpoint:
        uri: http://PARTS-ORDER-CLIENT-APP/parts/order/v1/getPartsOrderList
        
microservice:
  client2-service:
    endpoints:
      endpoint:
        uri: http://PARTS-ORDER-MANAGEMENT-APP/parts/management/v1/validateOrder
